#!/usr/bin/env ruby
require 'lib/vendor/trollop/trollop'
require 'remus'


options = Trollop::options do
  version "Remus 0.0.1 (c) 2010 Rocky Meza, William Scales"
  banner <<-EOS
Remus is a syntax highlighter

Usage:
       remus [options]
where [options] are:
EOS

  opt :filename, "A file to be colored, Remus will try to identify the language", :type => String
  opt :language, "The language of the code to be colored", :type => String
  opt :token_class, "The output format", :type => String
  opt :code, "Code to be colored", :type => String
  
end

if ! $stdin.tty? # if code is piped in
  options[:code] = $stdin.read unless $stdin.tty? # grab code that is piped in
  options[:language] = Remus.parse_shebang options[:code] if ! options[:language] # try to detect language
end

Trollop::die :language, 'No language detected, please specify a language' if ( options[:code] && ! options[:language] )

options.delete_if { |key,value| value.nil? } # remove empties
defaults = { :token_class => :sh } # defaults hash
options = defaults.merge options # merge options into defaults

if options[:code]
  
  puts Remus.convert( options[:code], options[:language], options )
  
elsif options[:filename]
  
  puts Remus.convert_from_file( options[:filename], options )
  
end

